"""Jericho Vault Module — Zero-knowledge secret storage."""

from .crypto import (
    decrypt,
    derive_master_key,
    encrypt,
    generate_id,
    generate_salt,
    generate_symmetric_key,
    hash_master_password,
    hash_password_for_storage,
    make_stretched_master_key,
    protect_symmetric_key,
    stretch_master_key,
    unprotect_symmetric_key,
    verify_password_against_storage,
)
from .models import (
    VaultChangePasswordRequest,
    VaultFolderCreate,
    VaultFolderResponse,
    VaultItemCreate,
    VaultItemResponse,
    VaultItemUpdate,
    VaultSyncResponse,
    VaultUnlockRequest,
    VaultUnlockResponse,
    VaultUserCreate,
    VaultUserLogin,
    VaultUserResponse,
)

__all__ = [
    "derive_master_key",
    "stretch_master_key",
    "make_stretched_master_key",
    "hash_master_password",
    "hash_password_for_storage",
    "verify_password_against_storage",
    "generate_symmetric_key",
    "protect_symmetric_key",
    "unprotect_symmetric_key",
    "encrypt",
    "decrypt",
    "generate_id",
    "generate_salt",
    "VaultUserCreate",
    "VaultUserLogin",
    "VaultUserResponse",
    "VaultSyncResponse",
    "VaultItemCreate",
    "VaultItemUpdate",
    "VaultItemResponse",
    "VaultFolderCreate",
    "VaultFolderResponse",
    "VaultUnlockRequest",
    "VaultUnlockResponse",
    "VaultChangePasswordRequest",
]
